version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
    variables:
        "VERSION_HIGH": "25"
    exportedVariables:
        - VERSION_LOW
        - VERSION_MEDIUM

#variables:
# "testEnv" : "testValue1"
#exportedVariables:
#  - testEnv
 
# inputArtifacts:
# - name: hello-dev-jar
# location: hello123.class

 
steps:
- type: Command
  name: "Build pipelines-java"
  timeoutInSeconds: 400
  command: |
    mvn clean install
    echo "Build Done"
  onFailure:
    - type: Command
      timeoutInSeconds: 400
      command: |
        echo "Handling Failure"
        echo "Failure successfully handled"
- type: Command
  name: "Set Variables"
  timeoutInSeconds: 30
  command: |
      export VERSION_MEDIUM=5
      export VERSION_LOW=13
  onFailure:
    - type: Command
      timeoutInSeconds: 400
      command: |
        echo "Handling Failure"
        echo "Failure successfully handled"

outputArtifacts:
- name: helloworld
  type: BINARY
  location: target/helloworld.war
